//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 05:36:53 PM IST 
//


package com.example.DM_Final;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Course complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Course">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="courseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="facultyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}Faculty" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Course", propOrder = {
    "id",
    "courseName",
    "facultyName",
    "faculty"
})
public class Course {

    protected int id;
    @XmlElement(required = true)
    protected String courseName;
    @XmlElement(required = true)
    protected String facultyName;
    @XmlElement(name = "Faculty", required = true)
    protected List<Faculty> faculty;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the courseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * Sets the value of the courseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseName(String value) {
        this.courseName = value;
    }

    /**
     * Gets the value of the facultyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyName() {
        return facultyName;
    }

    /**
     * Sets the value of the facultyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyName(String value) {
        this.facultyName = value;
    }

    /**
     * Gets the value of the faculty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the faculty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFaculty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Faculty }
     * 
     * 
     */
    public List<Faculty> getFaculty() {
        if (faculty == null) {
            faculty = new ArrayList<Faculty>();
        }
        return this.faculty;
    }

}
