//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.12 at 05:36:53 PM IST 
//


package com.example.DM_Final;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.DM_Final package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Faculty_QNAME = new QName("", "Faculty");
    private final static QName _Course_QNAME = new QName("", "Course");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.DM_Final
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Faculty }
     * 
     */
    public Faculty createFaculty() {
        return new Faculty();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Faculty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Faculty")
    public JAXBElement<Faculty> createFaculty(Faculty value) {
        return new JAXBElement<Faculty>(_Faculty_QNAME, Faculty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Course }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Course")
    public JAXBElement<Course> createCourse(Course value) {
        return new JAXBElement<Course>(_Course_QNAME, Course.class, null, value);
    }

}
